dist: xenial

language: python

addons:
  apt:
    packages:
      - doxygen
      - graphviz

deploy:
  provider: pypi
  user: bluerobotics
  distributions: sdist
  password:
    secure: aC6RbHIr4N8nR6zSEAyXCKNUHW8MWwNihb4IkM24qhXGXR0xk7lytxj8ILSKycIApMHeSe5cfJKBuk/g7cHrqqHWtAYYBsRlTKFlNbLwSUu5mEn5O9LS8/BkJC1n0mPedKMTHBjK1lRcDRaLaIDHBEPL6dNWT1NqCK5zO8w6rIWbLcHqhhZ5uSEo2Zl0NGKf8AISetNFqKYy/L7F4fe0sE+NAUl1wQjscJn3IjvUhRPQaYoVdc7ovfvkmhhh1xq18qsio707g5PxnUKYj+4K14lpyZgHlW3npxoQsCfqoVe4TxmW2O6Y8/dkfg3FcXNZMN1TLrfzeh0dJqmqOggBmkL5eq4nuZtCZeLHNKUmWyllrnvHHktwSBfz9AgdMSdF8B+g6N9lZOb+X/MEvs7qbRNNMgt50mxGcFOuyZr70tsXZGEPQAtOnnyUsCd/aWkm42G5wsXt5n2bkiZehpYyqSkVwx7zRnIZsB/T3dIQZFh0w1lxExlx9eVCQKTGe39o54763tVVSY1gN57WsQpeYjqdYYC2cWLApIB/f/F+kyBT8gui/+/VM+ND4VhpWQ7C+fiwYJPcT4o4MwHWVVhmd1xWK5lSZgFIva7VoQYis+mpCwjaidYTK8PxBoISIh5c/vS8Bz2sMD/OnWRvZ0EZbIBo1W95dauzfBgh2rfP2TM=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+.[0-9]+.[0-9]+.* && $(if grep -q "${BASH_REMATCH:1}" "$TRAVIS_BUILD_DIR/setup.py"; then echo 0; fi)

script:
  - ci/travis-ci-script.sh || travis_terminate 1
